# Generated by Django 3.2 on 2024-10-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=10)),
                ('telefono', models.IntegerField(max_length=9)),
                ('email', models.EmailField(max_length=70)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
    ]
