# Generated by Django 3.2 on 2024-10-25 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEstacionamiento', '0002_remove_clienteest_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteest',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')]),
        ),
    ]
