# Generated by Django 3.2 on 2024-11-15 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEstacionamiento', '0004_auto_20241110_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('no_activo', 'No Activo')], default='activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='clienteest',
            name='direccion',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='La direccion debe incluir el nombre y numero de la calle, no solo números.', regex='^(?!^\\d+$)[a-zA-Z0-9\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El modelo solo puede contener letras, numeros y espacios.', regex='^[a-zA-Z0-9\\s]+$'), django.core.validators.MaxLengthValidator(50, message='El modelo no debe exceder los 50 caracteres.')]),
        ),
    ]
